name: colbert
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - langchain=0.3.7
  - langchain-community=0.3.6
  - langchain-openai=0.2.8
  - openai=1.54.4
  - pyngrok=7.0.1
  - tiktoken=0.8.0
  - flask=3.0.0
  - pypdf2=3.0.1
  - pip:
      - origamibot==2.3.6

