name: colbert
channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - ninja=1.10.2
  - cudatoolkit=11.3
  - faiss-gpu==1.7.4
  - gcc=9.4.0
  - gxx=9.4.0
  - pip=21.0
  - pytorch=1.13.1
  - pytorch-cuda=11.3
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - langchain=0.0.335
  - openai=0.27.4
  - cuda=11.7.1
  - bs4=4.12.2
  - pyngrok=7.0.1
  - flask=3.0.0
  - pyjwt=2.4.0
  - python-dotenv=1.0.0
  - pip:
      - plotly=5.9.0
      - pyyaml==6.0
      - tokenizers==0.14.1
      - datasets==2.14.6
      - huggingface-hub==0.17.3
      - origamibot==2.3.6
      - pywin32==306
