"""Constants for the Telegram bot module."""

# Configuration
CONFIG_SCHEMA = "telegram"
NGROK_ADDRESS = "localhost:5000"
NGROK_PROTOCOL = "http"

# Bot Messages
MSG_START = "Bot started. Chat ID: {}"
MSG_HEALTHCHECK = "Bot is alive!"
MSG_SUGGESTIONS_ALLOWED = "Suggestions allowed"
MSG_SUGGESTIONS_STOPPED = "Suggestions stopped"
MSG_CONVERSATION_MODE = "Conversation mode activated"
MSG_ASSISTANT_MODE = "Assistant mode activated"
MSG_CLEARED = "Current publication cleared"
MSG_SUGGESTIONS_UPDATED = "Suggestions updated"
MSG_NO_SUGGESTIONS = "No suggestions available"
MSG_INVALID_INDEX = "Invalid index"
MSG_CURRENT_SUGGESTION = "Current suggestion:\n{}"
MSG_NO_CURRENT_SUGGESTION = "No suggestion selected"
MSG_PUBLISH_SUCCESS = "Published successfully!"
MSG_PUBLISH_FAILURE = "Failed to publish"
MSG_NEED_AUTH = "Authentication required. Please visit: {}"
MSG_PDF_SAVED = "PDF saved successfully"
MSG_YOUTUBE_ADDED = "YouTube URL added to pool"
MSG_INVALID_URL = "Invalid YouTube URL"
MSG_IMAGE_GENERATING = "Generating image..."
MSG_IMAGE_CLEARED = "Image cleared"
MSG_CONV_ID_NOT_SET = "Conversation ID must be set"
MSG_IMAGE_NOT_PASSED = "In order to set an image you need to pass an image in the message"
MSG_PROVIDE_INSTRUCTIONS = "Please provide instructions for the image change"
MSG_COMMAND_NOT_FOUND = "Command not found"
MSG_SEARCH_ENGINE_ACTIVATED = "Search engine activated successfully"
MSG_SEARCH_ENGINE_ACTIVATED_ERR = "Search engine could not be activated"
MSG_SEARCH_ENGINE_STOPPED = "Search engine stopped successfully"
MSG_SEARCH_ENGINE_STOPPED_ERR = "Search engine could not be stopped"
MSG_NO_IMAGES_FOR_PUBLICATION = "There are no images for this publication"
MSG_ERROR = "Something went wrong, try later :("
MSG_FILE_RECEIVED_SUCCESS = "File received successfully!"
MSG_IMAGE_RECEIVED_SUCCESS = "Image updated successfully"
MSG_ERROR_YOUTUBE = 'Error processing YouTube URL. Please try again.'
MSG_ERROR_COMMAND_BIND = 'Command failed to bind arguments!'
MSG_ERROR_LOADING_SUGGESTION = "Error loading next suggestion"
MSG_SAME_SUGGESTION_SELECTED = "You selected the same suggestion"
MSG_ERROR_SELECTING_SUGGESTION = "Error selecting suggestion"
MSG_ERROR_SENDING = "Error sending suggestion: {}"
MSG_ERROR_PUBLISH = "Failed to publish: {}"
MSG_ERROR_CLEAR = "Error clearing publication: {}"
MSG_ERROR_COMMAND = "Error in command: {}"
